source ~/projects/wal/dotfiles/bash/paths
source ~/projects/wal/dotfiles/bash/aliases
source ~/projects/wal/dotfiles/bash/functions
source ~/projects/wal/dotfiles/bash/completions
source ~/projects/wal/dotfiles/bash/prompt
source ~/projects/wal/dotfiles/bash/aws

eval "$(rbenv init -)"
. .bashrc

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
