source ~/projects/wal/dotfiles/bash/paths
source ~/projects/wal/dotfiles/bash/aliases
source ~/projects/wal/dotfiles/bash/functions
source ~/projects/wal/dotfiles/bash/completions
source ~/projects/wal/dotfiles/bash/config
source ~/projects/wal/dotfiles/bash/rvm

# Enable RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
